#!/usr/bin/env bash
set -euo pipefail

AGENTS_DIR="$(cd "$(dirname "$0")/.." && pwd)"
REPO_ROOT="$(cd "$AGENTS_DIR/.." && pwd)"
MODE="${1:-sync}"

case "$MODE" in
    sync|check|install-codex) ;;
    *)
        echo "Usage: $0 [sync|check|install-codex]" >&2
        exit 2
        ;;
esac

python3 - "$REPO_ROOT" "$MODE" <<'PY'
import json
import os
import re
import sys
import tempfile
from pathlib import Path

repo_root = Path(sys.argv[1])
mode = sys.argv[2]
source = repo_root / ".agents" / "mcp" / "servers.json"

try:
    servers = json.loads(source.read_text(encoding="utf-8"))
except (OSError, json.JSONDecodeError) as exc:
    raise SystemExit(f"ERROR: cannot read {source}: {exc}")

if not isinstance(servers, dict):
    raise SystemExit("ERROR: .agents/mcp/servers.json must contain a JSON object")
for name, config in servers.items():
    if not isinstance(name, str) or not name:
        raise SystemExit("ERROR: every MCP server must have a non-empty string name")
    if not isinstance(config, dict):
        raise SystemExit(f"ERROR: MCP server {name!r} must contain an object")


def json_document(value):
    return json.dumps(value, indent=2, ensure_ascii=False) + "\n"


def toml_key(value):
    if re.fullmatch(r"[A-Za-z0-9_-]+", value):
        return value
    return json.dumps(value, ensure_ascii=False)


def toml_value(value):
    if isinstance(value, str):
        # json.dumps escapes U+0000-U+001F but leaves U+007F raw, which TOML forbids.
        return json.dumps(value, ensure_ascii=False).replace("\x7f", "\\u007f")
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)) and not isinstance(value, bool):
        return repr(value)
    if isinstance(value, list):
        return "[" + ", ".join(toml_value(item) for item in value) + "]"
    if isinstance(value, dict):
        pairs = (f"{toml_key(key)} = {toml_value(item)}" for key, item in value.items())
        return "{ " + ", ".join(pairs) + " }"
    raise SystemExit(f"ERROR: unsupported TOML value in MCP config: {value!r}")


claude_servers = {}
cursor_servers = {}
for name, config in servers.items():
    claude_config = dict(config)
    if "url" in claude_config:
        claude_config.setdefault("type", "http")
    claude_servers[name] = claude_config

    cursor_config = dict(config)
    cursor_config.pop("type", None)
    cursor_servers[name] = cursor_config

codex_lines = ["# Generated by .agents/scripts/sync-mcp.sh; do not edit."]
for name, config in servers.items():
    codex_lines.extend(("", f"[mcp_servers.{toml_key(name)}]"))
    for key, value in config.items():
        if key == "type":
            continue
        codex_lines.append(f"{toml_key(key)} = {toml_value(value)}")

outputs = {
    repo_root / ".mcp.json": json_document({"mcpServers": claude_servers}),
    repo_root / ".cursor" / "mcp.json": json_document({"mcpServers": cursor_servers}),
    repo_root / ".codex" / "config.toml": "\n".join(codex_lines) + "\n",
}


def atomic_write(path, content):
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, temporary = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            handle.write(content)
        umask = os.umask(0)
        os.umask(umask)
        os.chmod(temporary, 0o666 & ~umask)
        os.replace(temporary, path)
    finally:
        if os.path.exists(temporary):
            os.unlink(temporary)


if mode == "check":
    stale = []
    for path, expected in outputs.items():
        try:
            current = path.read_text(encoding="utf-8")
        except OSError:
            current = None
        if current != expected:
            stale.append(path.relative_to(repo_root))
    if stale:
        print("Stale MCP adapters:", file=sys.stderr)
        for path in stale:
            print(f"  {path}", file=sys.stderr)
        print("Run .agents/scripts/sync-mcp.sh to regenerate them.", file=sys.stderr)
        raise SystemExit(1)
    print("MCP adapters are current.")
elif mode == "sync":
    for path, content in outputs.items():
        atomic_write(path, content)
        print(f"Generated: {path.relative_to(repo_root)}")
else:
    repo_name = re.sub(r"[^A-Za-z0-9_-]+", "-", repo_root.name).strip("-") or "repo"
    begin = f"# BEGIN {repo_name} managed MCP"
    end = f"# END {repo_name} managed MCP"
    block = begin + "\n" + outputs[repo_root / ".codex" / "config.toml"] + end
    user_config = Path.home() / ".codex" / "config.toml"
    try:
        current = user_config.read_text(encoding="utf-8")
    except FileNotFoundError:
        current = ""
    pattern = re.compile(
        rf"(?ms)^[ \t]*{re.escape(begin)}\n.*?^[ \t]*{re.escape(end)}[ \t]*\n?"
    )
    current = re.sub(r"\n{3,}", "\n\n", pattern.sub("", current)).rstrip()
    merged = (current + "\n\n" if current else "") + block + "\n"
    atomic_write(user_config, merged)
    print(f"Installed managed MCP block: {user_config}")
PY
